Porting to kernel 5.4
Fixed following error:
Implicit declaration of function 'mmiowb'
Caused by patch 'arm64/io: Remove useless definition of mmiowb()'.

Signed-off-by: Dmytro Prokopchuk <dmytro.prokopchuk@globallogic.com>
Jira-ID: ADM-4734
Change-Id: Iaecb5f53ee5e241a748ae194e1ddde2a5b3b85de